#2: Create POST /items
Chuva-Foundation/rating-api pull request #21
Opened 2023-08-04 11:11 UTC by vandro

2023-08-04 15:40 UTC, savylopes approved these changes

2023-08-04 15:45 UTC, savylopes requested changes
@vandro please check if all attribute corresponded to the category attributes have the values provided

2023-08-07 18:07 UTC, RonyGomesK78 approved these changes

2023-08-07 18:08 UTC, RonyGomesK78 approved these changes

2023-08-07 18:26 UTC, merged